repos:
  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black-format
        types_or: [python]
        exclude: ^features/template/

  # Bandit security linting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        name: bandit-security
        types_or: [python]
        args: ['--skip', 'B101,B112,B404,B603,B607']
        exclude: ^(tests/|test_|features/template/)

  # MyPy static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy-type-check
        types_or: [python]
        additional_dependencies: [types-PyYAML, types-requests]
        exclude: ^features/template/

  # Ruff check (linting; keep after format so auto-fixes run first)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff-check
        types_or: [python]
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: []  # keep empty unless you need extras

  # Local hooks for documentation coverage
  - repo: local
    hooks:
      - id: readme-coverage
        name: README coverage (LLM-First)
        entry: python3
        language: system
        pass_filenames: false
        files: ""  # run always
        stages: [pre-commit]
        args: ["scripts/check_readme_coverage.py"]
      - id: frontmatter-coverage
        name: Frontmatter coverage (LLM-First)
        entry: python3
        language: system
        pass_filenames: false
        files: ""  # run always
        stages: [pre-commit]
        args: ["scripts/validate_schemas.py", "--check-source-files"]

# Global excludes to speed up hooks that still look at repo root
exclude: |
  (?x)(
    ^\.git/|
    ^\.venv/|^venv/|
    ^node_modules/|
    ^dist/|^build/|
    ^\.mypy_cache/|^\.ruff_cache/|^\.pytest_cache/|^\.tox/|
    ^\.next/
  )