[tool.ruff]
target-version = "py311"
line-length = 100
# Choose your rule sets; "ALL" is strict. This is a balanced set.
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "SIM" # flake8-simplify
]
ignore = [
  # Add ignores if the codebase needs; keep minimal.
  "E203", # space before ':', compatible with black/formatters
]

# Exclude heavy or generated dirs
exclude = [
  ".git",
  ".venv",
  "venv",
  "node_modules",
  "dist",
  "build",
  ".mypy_cache",
  ".ruff_cache",
  ".pytest_cache",
  ".tox",
  ".next",
  "features/template",  # Template files contain placeholders, not valid Python
]

[tool.ruff.lint.isort]
known-first-party = ["src", "features", "scripts"]  # adjust to your modules

[tool.pytest.ini_options]
testpaths = ["scripts", "features"]
python_files = "test_*.py"
addopts = "-v --tb=short"